/**
 * Linkable spontaneous anonymous group signatures (spec section 6).
 *
 * Ported from the Python implementation, which was written from Liu-Wei-Wong
 * (ACISP 2004). The research prototype's ring signature is **not** LSAG and was
 * not used as a reference: it computes `R_i` and discards it, and its
 * hash-to-point is `SHA256(P) * G`.
 *
 * A signature proves the signer is *some* member of a ring without revealing
 * which, and carries a key image `I = x * H_p(P)` that is deterministic per
 * secret key. Two signatures with equal key images came from the same key,
 * which is the entire double-vote detection mechanism.
 *
 * Four defects of the research prototype are fixed structurally here:
 *
 * - **C1** `H_p` is RFC 9380 hash-to-curve, so `log_G(H_p(P))` is unknown.
 * - **C2** The challenge binds `R_i`, `I`, and the ring, so no forged key image
 *   can satisfy the closure.
 * - **C3** {@link lsagVerify} takes the ring as a required argument and
 *   {@link RingSignature} has no ring field, so an attacker-supplied ring is
 *   unrepresentable rather than merely discouraged.
 * - **C4** Nonces come from the platform CSPRNG.
 *
 * The ring loop runs exactly `n - 1` times for every signer index. The research
 * prototype's bound ran `2n - 1` times when the signer sat at the last index,
 * wrapping almost twice around the ring and overwriting the signer's own slot.
 * That is the real cause of its "ring must have n+1 keys" workaround.
 */

import { sha256 } from '@noble/hashes/sha2.js';

import { DST_H2C, DST_LSAG, DST_RING } from '../domain.js';
import { InvalidRingError, ValidationError } from '../errors.js';
import {
  bytesToHex,
  concatBytes,
  encBytes,
  encU32,
  hexToBytes,
  os2ip,
} from '../serialization/encoding.js';
import {
  CURVE_ORDER,
  G,
  add,
  decodePoint,
  encodePoint,
  isInPrimeOrderSubgroup,
  mul,
  randomScalar,
  type Point,
} from './curve.js';
import { hashToCurve } from './hashToCurve.js';

/** Above this the electorate is partitioned into sub-rings; cost is O(n). */
export const MAX_RING = 1000;

/**
 * A voter's keypair.
 *
 * Generated by the voter, never by a committee. An API that mints keys on
 * voters' behalf hands whoever calls it the ability to forge every ballot and
 * de-anonymize every voter, which is break **C6**; no such function exists in
 * this package.
 */
export interface VoterKey {
  readonly secret: bigint;
  readonly public: Point;
  /** Always throws. Voter keys must not be persisted by this library. */
  toJSON(): never;
}

/**
 * A ring signature.
 *
 * Deliberately has **no ring field**. The ring is election data obtained from
 * the published parameters; taking it from the signature is break C3.
 */
export interface RingSignature {
  readonly keyImage: Point;
  readonly c0: bigint;
  readonly responses: readonly bigint[];
}

export function makeVoterKey(secret: bigint, publicKey: Point): VoterKey {
  const encoded = bytesToHex(encodePoint(publicKey));
  return {
    secret,
    public: publicKey,
    toJSON(): never {
      throw new ValidationError('a voter key must not be serialized by the library');
    },
    toString: () => `VoterKey(public=${encoded}, secret=<redacted>)`,
    [Symbol.for('nodejs.util.inspect.custom')]: () =>
      `VoterKey(public=${encoded}, secret=<redacted>)`,
  } as VoterKey;
}

/** Generate a voter keypair. Voter-side only. */
export function ringKeygen(): VoterKey {
  const x = randomScalar();
  return makeVoterKey(x, mul(G, x));
}

const hashToPointCache = new Map<string, Point>();

/**
 * `H_p(P)` -- RFC 9380 hash-to-curve of the compressed encoding.
 *
 * Cached by encoded public key. `H_p` is called `2n` times per ring operation
 * and depends only on the ring, which is fixed for a whole election, so without
 * this cache the browser performance budgets are unreachable.
 */
export function hashToPoint(point: Point): Point {
  const encoded = encodePoint(point);
  const key = bytesToHex(encoded);
  const cached = hashToPointCache.get(key);
  if (cached) return cached;
  const result = hashToCurve(encoded, DST_H2C);
  // Bounded so a long-lived page cannot grow the cache without limit.
  if (hashToPointCache.size >= 4096) hashToPointCache.clear();
  hashToPointCache.set(key, result);
  return result;
}

/** `I = x * H_p(P)`. Deterministic per secret key. */
export function computeKeyImage(key: VoterKey): Point {
  return mul(hashToPoint(key.public), key.secret);
}

/**
 * Sort into canonical order and reject duplicates.
 *
 * Ascending lexicographic order of the compressed encodings, so any verifier can
 * reproduce `ringHash` from the published electorate without being told the
 * order.
 */
export function canonicalRing(members: readonly Point[]): Point[] {
  const encoded = members.map((p) => bytesToHex(encodePoint(p)));
  if (new Set(encoded).size !== encoded.length) {
    throw new InvalidRingError('ring contains duplicate public keys');
  }
  return [...encoded].sort().map((hex) => decodePoint(hexToBytes(hex)));
}

/** `SHA256(DST_RING || Enc_u32(n) || Enc_point(P_0) || ... )`. */
export function ringHash(ring: readonly Point[]): Uint8Array {
  return sha256(concatBytes(DST_RING, encU32(ring.length), ...ring.map(encodePoint)));
}

/**
 * `H_c(m, I, L, R) mod q`.
 *
 * `R` and `I` are bound, which is what constrains the key image. Points use the
 * full 33-byte compressed encoding rather than the x-coordinate alone,
 * otherwise `L` and `-L` would collide.
 */
function challenge(
  rh: Uint8Array,
  keyImage: Point,
  message: Uint8Array,
  left: Point,
  right: Point,
): bigint {
  const digest = sha256(
    concatBytes(
      DST_LSAG,
      rh,
      encodePoint(keyImage),
      encBytes(message),
      encodePoint(left),
      encodePoint(right),
    ),
  );
  return os2ip(digest) % CURVE_ORDER;
}

function validateRing(ring: readonly Point[]): Uint8Array {
  if (ring.length < 2) {
    throw new InvalidRingError(`ring must have at least 2 members, got ${ring.length}`);
  }
  const encoded = ring.map((p) => bytesToHex(encodePoint(p)));
  if (new Set(encoded).size !== encoded.length) {
    throw new InvalidRingError('ring contains duplicate public keys');
  }
  const sorted = [...encoded].sort();
  for (let i = 0; i < encoded.length; i++) {
    if (encoded[i] !== sorted[i]) throw new InvalidRingError('ring is not in canonical order');
  }
  return ringHash(ring);
}

export interface SignOptions {
  /** Invoked with a 0..1 fraction as the ring loop advances. */
  readonly onProgress?: (fraction: number) => void;
  readonly signal?: AbortSignal;
}

/** Sign `message` as an unidentified member of `ring`. */
export function lsagSign(
  message: Uint8Array,
  ring: readonly Point[],
  signerIndex: number,
  key: VoterKey,
  options: SignOptions = {},
): RingSignature {
  const rh = validateRing(ring);
  const n = ring.length;
  if (!(signerIndex >= 0 && signerIndex < n)) {
    throw new InvalidRingError(`signer index ${signerIndex} outside ring of size ${n}`);
  }
  if (!(ring[signerIndex] as Point).equals(key.public)) {
    throw new ValidationError('signer index does not hold the signer\'s public key');
  }

  const keyImage = computeKeyImage(key);
  const u = randomScalar();

  const c = new Array<bigint>(n).fill(0n);
  const responses = new Array<bigint>(n).fill(0n);
  c[(signerIndex + 1) % n] = challenge(
    rh,
    keyImage,
    message,
    mul(G, u),
    mul(hashToPoint(key.public), u),
  );

  // Exactly n - 1 iterations, for every signer index.
  for (let step = 1; step < n; step++) {
    options.signal?.throwIfAborted();
    const i = (signerIndex + step) % n;
    const response = randomScalar();
    responses[i] = response;
    const member = ring[i] as Point;
    const ci = c[i] as bigint;
    const left = add(mul(G, response), mul(member, ci));
    const right = add(mul(hashToPoint(member), response), mul(keyImage, ci));
    c[(i + 1) % n] = challenge(rh, keyImage, message, left, right);
    options.onProgress?.(step / n);
  }

  // Close the ring: only the true secret can produce this response.
  const cs = c[signerIndex] as bigint;
  responses[signerIndex] = (((u - key.secret * cs) % CURVE_ORDER) + CURVE_ORDER) % CURVE_ORDER;
  options.onProgress?.(1);
  return { keyImage, c0: c[0] as bigint, responses };
}

/**
 * Verify a ring signature against a ring supplied by the caller.
 *
 * The ring is a **required argument** and must come from the election
 * parameters. Reading it from the signature -- as the research prototype did --
 * lets an attacker submit a ring of size one containing only a key they just
 * generated, which verifies perfectly and yields a fresh key image every time:
 * unlimited ballot stuffing.
 *
 * Never throws.
 */
export function lsagVerify(
  message: Uint8Array,
  ring: readonly Point[],
  sig: RingSignature,
  options: SignOptions = {},
): boolean {
  const n = ring.length;
  if (n < 2 || sig.responses.length !== n) return false;

  let rh: Uint8Array;
  try {
    rh = validateRing(ring);
  } catch {
    return false;
  }

  if (!(sig.c0 >= 0n && sig.c0 < CURVE_ORDER)) return false;
  for (const r of sig.responses) {
    if (!(r >= 0n && r < CURVE_ORDER)) return false;
  }
  if (sig.keyImage.is0() || !isInPrimeOrderSubgroup(sig.keyImage)) return false;

  try {
    let c = sig.c0;
    for (let i = 0; i < n; i++) {
      options.signal?.throwIfAborted();
      const member = ring[i] as Point;
      const response = sig.responses[i] as bigint;
      const left = add(mul(G, response), mul(member, c));
      const right = add(mul(hashToPoint(member), response), mul(sig.keyImage, c));
      c = challenge(rh, sig.keyImage, message, left, right);
      options.onProgress?.((i + 1) / n);
    }
    return c === sig.c0;
  } catch {
    return false;
  }
}

/**
 * Whether two signatures were produced by the same secret key.
 *
 * Sound only because `H_p` is a real hash-to-curve (C1) and the key image is
 * bound into the challenge (C2). In the research prototype this comparison was
 * meaningless: the image was both publicly computable and unconstrained.
 */
export function lsagLink(a: RingSignature, b: RingSignature): boolean {
  return a.keyImage.equals(b.keyImage);
}

/**
 * Deterministic sub-ring assignment for electorates above {@link MAX_RING}.
 *
 * Anonymity degrades from "one of n" to "one of the sub-ring size", which must
 * be surfaced to the voter rather than left implicit.
 */
export function subringIndex(
  publicKey: Point,
  electionId: Uint8Array,
  numSubrings: number,
): number {
  if (numSubrings < 1) throw new ValidationError('numSubrings must be at least 1');
  const digest = sha256(
    concatBytes(
      DST_RING,
      new TextEncoder().encode('PARTITION'),
      electionId,
      encodePoint(publicKey),
    ),
  );
  return Number(os2ip(digest) % BigInt(numSubrings));
}
